# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  watch:
    types: [started]

env:
  Version: 2.1.5
  TZ: Asia/Shanghai

jobs:
  # ubuntu_build:
  #   runs-on: ubuntu-latest
  #   if: github.event.repository.owner.id == github.event.sender.id

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@master
    
  #   - name: build
  #     run: |
  #       sudo apt-get -qq update
  #       sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
  #       sudo apt-get install --no-install-recommends -y rpm nodejs npm
  #       npm install
  #       npm run build
  #       npm run release

  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@master
  #     if: ${{ always() }}
  #     with:
  #       name: ubuntu_build_bin
  #       path: /home/runner/work/dingtalk/dingtalk/release


  win_build:
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          yarn build
          yarn release
    
      - name: Copy exe
        if: ${{ always() }}
        run: |
          md bin
          copy ./release/*.exe ./release/bin/

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: win_build_bin
          path: ./release/bin

  # test_build:
  #   runs-on: windows-latest
  #   if: github.event.repository.owner.id == github.event.sender.id

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'
    
  #     - name: Copy exe
  #       if: ${{ always() }}
  #       run: |
  #         echo 当前目录是:%cd%
  #         md bin
  #         copy ./*.js ./bin
  #         cd ./bin
  #         dir