# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
    
    - name: build
      run: |
        sudo apt-get -qq update
        sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
        sudo apt-get install --no-install-recommends -y rpm
        npm install
        npm run release
        
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: download url
        path: ./release
