# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: build
      run: |
        sudo apt-get -qq update
        sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
        sudo apt-get install --no-install-recommends -y rpm
        npm install
        npm run release
        
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: download url
        path: ./release
